import Link from "next/link"
//import globals.css
import "./globals.css"
//import font awesome
import "@fortawesome/fontawesome-svg-core/styles.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="lemonade" >
      <body>
        {/* area header */}
        <header>
          <div className="navbar bg-base-100">
            <div className="flex-1">
              <Link href={"/admin"} className="btn btn-ghost text-xl">Admin Controller</Link>
              <Link href={"/barang"} className="btn btn-ghost text-xl">Item Controller</Link>
              
            </div>
            <div className="flex-none gap-2">
              <div className="form-control">
                <input type="text" placeholder="Search" className="input input-bordered w-24 md:w-auto" />
              </div>
              <div className="dropdown dropdown-end">
                <div tabIndex={0} role="button" className="btn btn-ghost btn-circle avatar">
                  <div className="w-10 rounded-full">
                    <img
                      alt="Tailwind CSS Navbar component"
                      src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
                  </div>
                </div>
                <ul
                  tabIndex={0}
                  className="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
                  <li>
                    <a className="justify-between">
                      Profile
                      <span className="badge">New</span>
                    </a>
                  </li>
                  <li><a>Settings</a></li>
                  <li><a>Logout</a></li>
                </ul>
              </div>
            </div>
          </div>

        </header>

        {/* area konten */}
        <section className="m-5">{children}</section>


        {/* area footer */}
        <footer className="flex justify-center bg-color1 text-color3-1 py-15x">

        </footer>
      </body>

    </html>
  )
}
